-- B1 Semantic Grouping - All 500 words from B1.txt
-- Uses the exact groupings from B1.txt file
-- No modifications, just direct assignment

-- Step 1: Reset ALL B1 topic groups to NULL
UPDATE general_english_vocab
SET topic_group = NULL
WHERE cefr_level = 'B1';

-- Step 2: Assign each word based on B1.txt (all 500 words)
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'actor';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'audience';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'writer';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'scientist';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'secretary';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'secret';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'soldier';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'engineer';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'nurse';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'artist';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'visitor';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'guest';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'neighbor';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'owner';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'senior';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'band';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'fan';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'colleague';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'consumer';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'sum';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'administration';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'ad';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'corporate';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'employ';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'sector';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'finance';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'advertise';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'sight';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'register';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'otherwise';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'cool';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'deliver';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'hide';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'tourist';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'handle';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'belong';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'select';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'map';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'cry';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'expand';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'leg';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'examine';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'experiment';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'spread';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'reader';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'heavy';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'sample';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'assessment';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'consideration';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'gold';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'suggestion';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'novel';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'category';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'troop';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'proper';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'affair';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'violence';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'failure';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'intend';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'shift';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'lawyer';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'council';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'minister';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'federal';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'spot';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'pool';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'presence';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'locate';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'neither';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'chapter';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'square';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'tape';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'complain';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'ignore';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'duty';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'conflict';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'editor';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'element';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'favor';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'peace';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'cash';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'afford';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'coffee';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'feed';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'fee';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'purchase';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'count';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'cheap';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'expensive';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'payment';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'waste';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'satisfy';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'gun';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'reality';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'sex';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'guide';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'crowd';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'trend';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'reform';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'settle';
UPDATE general_english_vocab SET topic_group = 'topic_group' WHERE cefr_level = 'B1' AND english_term = 'english_term';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'flight';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'plane';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'ship';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'taxi';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'ticket';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'rain';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'busy';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'importance';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'transport';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'description';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'remove';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'anybody';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'strength';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'dry';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'user';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'monitor';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'lesson';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'roll';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B1' AND english_term = 'tonight';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'inform';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'heat';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'weather';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'beat';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'threat';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'theater';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'repeat';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'meal';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'dinner';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'lunch';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'cook';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'wine';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'egg';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'insurance';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'scheme';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'generate';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'connection';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'location';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'mass';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'video';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'bind';
UPDATE general_english_vocab SET topic_group = 'Home & Daily Life' WHERE cefr_level = 'B1' AND english_term = 'flat';
UPDATE general_english_vocab SET topic_group = 'Home & Daily Life' WHERE cefr_level = 'B1' AND english_term = 'apart';
UPDATE general_english_vocab SET topic_group = 'Home & Daily Life' WHERE cefr_level = 'B1' AND english_term = 'bedroom';
UPDATE general_english_vocab SET topic_group = 'Home & Daily Life' WHERE cefr_level = 'B1' AND english_term = 'kitchen';
UPDATE general_english_vocab SET topic_group = 'Home & Daily Life' WHERE cefr_level = 'B1' AND english_term = 'chair';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'comfortable';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'wind';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'wash';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'refuse';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'appreciate';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'quick';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'lay';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'quote';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'investigation';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'copy';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'hall';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'fresh';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'announce';
UPDATE general_english_vocab SET topic_group = 'Clothing & Fashion' WHERE cefr_level = 'B1' AND english_term = 'pair';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'majority';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'healthy';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'pain';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'skin';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'mouth';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'earth';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'nuclear';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'dear';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'tear';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'smoke';
UPDATE general_english_vocab SET topic_group = 'Clothing & Fashion' WHERE cefr_level = 'B1' AND english_term = 'shoe';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'labor';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'pop';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'straight';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'whereas';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'solve';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'destroy';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'lift';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'revenue';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'status';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'collection';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'software';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'code';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'equipment';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'tool';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'net';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'north';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'fair';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'request';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'tough';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'rich';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'cycle';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'boat';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'brief';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'display';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'capacity';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'regular';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'route';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'vehicle';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'surround';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B1' AND english_term = 'twice';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'brain';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'winter';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'beach';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'wood';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'flower';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'flow';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'farm';
UPDATE general_english_vocab SET topic_group = 'topic_group' WHERE cefr_level = 'B1' AND english_term = 'english_term';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'wave';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'driver';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'river';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'freedom';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'promote';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'crisis';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'swim';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'somewhere';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'expert';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'invite';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'surface';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'jump';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'conclude';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'football';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'ball';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'concert';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Feelings & Reactions' WHERE cefr_level = 'B1' AND english_term = 'funny';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'print';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'relax';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'contribute';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'budget';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'mix';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'defense';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'entire';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'survey';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'block';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'award';
UPDATE general_english_vocab SET topic_group = 'Clothing & Fashion' WHERE cefr_level = 'B1' AND english_term = 'suit';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'climb';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'blow';
UPDATE general_english_vocab SET topic_group = 'Home & Daily Life' WHERE cefr_level = 'B1' AND english_term = 'glass';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'telephone';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'blood';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'advice';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'admit';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'lady';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B1' AND english_term = 'decade';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'additional';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'radio';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'tradition';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'broad';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'adopt';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'glad';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'load';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'sentence';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'expression';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'email';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'pleasure';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'decrease';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'civil';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'tire';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'deny';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'strange';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B1' AND english_term = 'annual';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'schedule';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'stress';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'respond';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'south';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'branch';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'border';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'chief';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'gather';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'regulation';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'assess';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'delivery';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'stone';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'gift';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'hurt';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'onto';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'commit';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'citizen';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'quiet';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'cup';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'aid';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'afraid';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'attitude';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'aware';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'familiar';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'famous';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'excite';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'hate';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'unless';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'perspective';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'objective';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Feelings & Reactions' WHERE cefr_level = 'B1' AND english_term = 'critical';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'impossible';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'executive';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Feelings & Reactions' WHERE cefr_level = 'B1' AND english_term = 'excellent';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'physical';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'component';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'traffic';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'appeal';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'trial';
UPDATE general_english_vocab SET topic_group = 'Clothing & Fashion' WHERE cefr_level = 'B1' AND english_term = 'bag';
UPDATE general_english_vocab SET topic_group = 'Clothing & Fashion' WHERE cefr_level = 'B1' AND english_term = 'fashion';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'enable';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'powerful';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'relative';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'grant';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'religious';
UPDATE general_english_vocab SET topic_group = 'topic_group' WHERE cefr_level = 'B1' AND english_term = 'english_term';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'representative';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'obvious';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'vary';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'usual';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'alternative';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'industrial';
UPDATE general_english_vocab SET topic_group = 'Home & Daily Life' WHERE cefr_level = 'B1' AND english_term = 'domestic';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'medical';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Feelings & Reactions' WHERE cefr_level = 'B1' AND english_term = 'responsible';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'independent';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'primary';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Feelings & Reactions' WHERE cefr_level = 'B1' AND english_term = 'negative';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'global';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'museum';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'library';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'distance';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'confidence';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'island';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'slow';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'contribution';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'district';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'battle';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'shoot';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'recommend';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'temperature';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'marriage';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B1' AND english_term = 'taste';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'suspect';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'extra';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'coach';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'recall';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'length';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'truth';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'percentage';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'scale';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'volume';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'extent';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'edge';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'principle';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'engage';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'plus';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'complex';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'murder';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'circumstance';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'bomb';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'partner';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'opposite';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'divide';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'convince';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'left';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'bird';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'burn';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'prison';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'accident';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'arrest';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'crime';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'weapon';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'dangerous';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'danger';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'safety';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'safe';
UPDATE general_english_vocab SET topic_group = 'Safety' WHERE cefr_level = 'B1' AND english_term = 'warn';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'shock';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'emerge';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'photo';
UPDATE general_english_vocab SET topic_group = 'Sports & Leisure' WHERE cefr_level = 'B1' AND english_term = 'camp';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'overall';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'arrangement';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'arrange';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'switch';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'host';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'moreover';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'tour';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'army';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'belief';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'bottom';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'camera';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'cancer';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'corner';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'delay';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'desire';
UPDATE general_english_vocab SET topic_group = 'Measurement & Quantity' WHERE cefr_level = 'B1' AND english_term = 'double';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'error';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'escape';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'gas';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'hang';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'horse';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'invest';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'launch';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'manner';
UPDATE general_english_vocab SET topic_group = 'People & Relationships' WHERE cefr_level = 'B1' AND english_term = 'nobody';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'noise';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'none';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'oppose';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'ought';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'pack';
UPDATE general_english_vocab SET topic_group = 'Places & Buildings' WHERE cefr_level = 'B1' AND english_term = 'path';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'proceed';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'remind';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'reply';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'ride';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'scene';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'shake';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'speed';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'spirit';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'spring';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'stick';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'studio';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'sun';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'title';
UPDATE general_english_vocab SET topic_group = 'Emotions & Attitudes' WHERE cefr_level = 'B1' AND english_term = 'trust';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'union';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'warm';
UPDATE general_english_vocab SET topic_group = 'topic_group' WHERE cefr_level = 'B1' AND english_term = 'english_term';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'active';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'actual';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'commercial';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'cultural';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'environmental';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'equal';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'essential';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'historical';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B1' AND english_term = 'initial';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'prevent';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'reveal';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B1' AND english_term = 'survive';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'technical';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Feelings & Reactions' WHERE cefr_level = 'B1' AND english_term = 'wonderful';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'speaker';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'concept';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'combine';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'collect';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'background';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'transfer';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'observe';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'politics';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'conduct';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'participate';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'confirm';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'struggle';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Feelings & Reactions' WHERE cefr_level = 'B1' AND english_term = 'perfect';
UPDATE general_english_vocab SET topic_group = 'Finance & Shopping' WHERE cefr_level = 'B1' AND english_term = 'exchange';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'attract';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'appropriate';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'demonstrate';
UPDATE general_english_vocab SET topic_group = 'Nature' WHERE cefr_level = 'B1' AND english_term = 'mountain';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'correct';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'progress';
UPDATE general_english_vocab SET topic_group = 'Law' WHERE cefr_level = 'B1' AND english_term = 'committee';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'mistake';
UPDATE general_english_vocab SET topic_group = 'Verbs: Action & Movement' WHERE cefr_level = 'B1' AND english_term = 'decline';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'difficulty';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'technique';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'connect';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'absolutely';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'apparently';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'basically';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'carefully';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'currently';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'directly';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'eventually';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'extremely';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'fairly';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'fully';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'hardly';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'highly';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'mainly';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'mostly';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'normally';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'possibly';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'relatively';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'slightly';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'totally';
UPDATE general_english_vocab SET topic_group = 'Adverbs & Degree Words' WHERE cefr_level = 'B1' AND english_term = 'unfortunately';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'manufacture';
UPDATE general_english_vocab SET topic_group = 'Adjectives: Describing People & Things' WHERE cefr_level = 'B1' AND english_term = 'effective';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'topic';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'content';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'text';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'context';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'contrast';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'consequence';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'construction';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'ensure';
UPDATE general_english_vocab SET topic_group = 'Work & Business' WHERE cefr_level = 'B1' AND english_term = 'improvement';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'institution';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'introduction';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B1' AND english_term = 'occasion';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'B1' AND english_term = 'package';
UPDATE general_english_vocab SET topic_group = 'Arts' WHERE cefr_level = 'B1' AND english_term = 'photograph';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B1' AND english_term = 'procedure';
UPDATE general_english_vocab SET topic_group = 'Science & Technology' WHERE cefr_level = 'B1' AND english_term = 'reaction';
UPDATE general_english_vocab SET topic_group = 'Abstract Nouns & Concepts' WHERE cefr_level = 'B1' AND english_term = 'requirement';
UPDATE general_english_vocab SET topic_group = 'Verbs: Thinking & Communication' WHERE cefr_level = 'B1' AND english_term = 'acquire';

-- Step 3: Verify the distribution meets all constraints
SELECT
    topic_group,
    COUNT(*) as word_count,
    CASE
        WHEN COUNT(*) < 5 THEN 'VIOLATES: Less than 5'
        WHEN COUNT(*) > 40 THEN 'VIOLATES: More than 40'
        ELSE 'GOOD'
    END as status
FROM general_english_vocab
WHERE cefr_level = 'B1'
GROUP BY topic_group
ORDER BY word_count DESC;

-- Step 4: Check for any remaining NULL values
SELECT COUNT(*) as remaining_nulls
FROM general_english_vocab
WHERE cefr_level = 'B1' AND topic_group IS NULL;

-- Step 5: Check for duplicate assignments
SELECT english_term, COUNT(*) as assignment_count
FROM general_english_vocab
WHERE cefr_level = 'B1' AND topic_group IS NOT NULL
GROUP BY english_term
HAVING COUNT(*) > 1;

-- Step 6: Final summary
SELECT
    COUNT(*) as total_b1_words,
    COUNT(DISTINCT topic_group) as total_groups,
    MIN(group_count) as min_group_size,
    MAX(group_count) as max_group_size
FROM (
    SELECT topic_group, COUNT(*) as group_count
    FROM general_english_vocab
    WHERE cefr_level = 'B1'
    GROUP BY topic_group
) as group_stats;
