-- B2 Final Semantic Grouping
-- Assigns topic groups to 610 B2 words across 36 semantic groups
-- Validated: No duplicates, clean assignment
-- Ready for manual addition of remaining 25 words

-- Step 1: Reset ALL B2 topic groups to NULL
UPDATE general_english_vocab
SET topic_group = NULL
WHERE cefr_level = 'B2';

-- Step 2: Assign topic groups to B2 words

UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'acknowledge';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'analyze';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'assumption';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'calculate';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'concentrate';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'concentration';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'confuse';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'consist';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'implication';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'intellectual';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'intelligence';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'interpretation';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'investigate';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'justify';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'observation';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'perceive';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'predict';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'resolve';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'scientific';
UPDATE general_english_vocab SET topic_group = 'Thinking & Knowing' WHERE cefr_level = 'B2' AND english_term = 'underlie';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'advise';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'communicate';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'command';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'declare';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'definition';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'explanation';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'hi';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'highlight';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'illustrate';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'imply';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'interaction';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'joke';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'laughter';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'phrase';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'remark';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'shout';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'silence';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'spell';
UPDATE general_english_vocab SET topic_group = 'Communication & Language' WHERE cefr_level = 'B2' AND english_term = 'tone';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'amaze';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'angry';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'bore';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'bother';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'calm';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'comfort';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'delight';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'depression';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'disappoint';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'emotion';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'emotional';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'fascinate';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'grateful';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'mood';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'nervous';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'proud';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'sad';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'satisfaction';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'B2' AND english_term = 'upset';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'alive';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'bone';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'breast';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'breath';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'breathe';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'ear';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'finger';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'ill';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'illness';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'injury';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'joint';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'medicine';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'mental';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'neck';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'nose';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'recover';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'shoulder';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'sick';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'smell';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'symptom';
UPDATE general_english_vocab SET topic_group = 'Health & Body' WHERE cefr_level = 'B2' AND english_term = 'tooth';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'assistant';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'boss';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'chairman';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'crew';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'employer';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'farmer';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'governor';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'investor';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'journalist';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'manufacturer';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'pilot';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'politician';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'producer';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'professor';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'reporter';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'researcher';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'specialist';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'supplier';
UPDATE general_english_vocab SET topic_group = 'People & Roles (Professional)' WHERE cefr_level = 'B2' AND english_term = 'volunteer';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'academic';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'critic';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'dad';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'elderly';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'fellow';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'folk';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'gay';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'gentleman';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'hero';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'king';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'master';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'minority';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'mom';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'native';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'ourselves';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'passenger';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'participant';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'peer';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'pupil';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'resident';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'self';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'supporter';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'winner';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'witness';
UPDATE general_english_vocab SET topic_group = 'People & Roles (General)' WHERE cefr_level = 'B2' AND english_term = 'youth';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'accuse';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'abuse';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'ban';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'blame';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'criminal';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'defeat';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'defend';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'dispute';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'enemy';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'guilty';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'judgment';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'justice';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'prisoner';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'protest';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'reject';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'steal';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'terrorist';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'threaten';
UPDATE general_english_vocab SET topic_group = 'Law, Crime & Conflict' WHERE cefr_level = 'B2' AND english_term = 'victim';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'conservative';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'democracy';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'elect';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'legislation';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'liberal';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'opposition';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'permit';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'poll';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'presidential';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'revolution';
UPDATE general_english_vocab SET topic_group = 'Politics & Governance' WHERE cefr_level = 'B2' AND english_term = 'voter';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'asset';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'brand';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'commission';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'corporation';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'debt';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'discount';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'enterprise';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'expense';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'export';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'import';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'loan';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'pension';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'retail';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'salary';
UPDATE general_english_vocab SET topic_group = 'Business & Finance' WHERE cefr_level = 'B2' AND english_term = 'wage';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'appointment';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'employment';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'hire';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'initiative';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'leadership';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'mission';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'occupy';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'recruit';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'retire';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'retirement';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'session';
UPDATE general_english_vocab SET topic_group = 'Work & Employment' WHERE cefr_level = 'B2' AND english_term = 'unemployment';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'attach';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'capture';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'crash';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'hunt';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'kick';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'kiss';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'knock';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'lean';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'lock';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'pour';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'rush';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'sail';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'shut';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'sink';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'slide';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'slip';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'stare';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'stretch';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'swing';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'tie';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Motion' WHERE cefr_level = 'B2' AND english_term = 'wake';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'abandon';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'alter';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'arise';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'collapse';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'complicate';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'construct';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'convert';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'derive';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'disappear';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'enhance';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'explore';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'freeze';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'implement';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'incorporate';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'install';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'integrate';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'preserve';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'restore';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'split';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'succeed';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'undertake';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'update';
UPDATE general_english_vocab SET topic_group = 'Verbs of Change & Development' WHERE cefr_level = 'B2' AND english_term = 'yield';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'accompany';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'appoint';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'approve';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'assist';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'assistance';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'assure';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'bet';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'celebrate';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'compete';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'competitive';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'cope';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'deserve';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'devote';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'dominate';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'emphasize';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'encounter';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'expose';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'impose';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'inspire';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'insist';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'negotiate';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'persuade';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'pursue';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'qualify';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'rely';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'urge';
UPDATE general_english_vocab SET topic_group = 'Formal & Social Actions' WHERE cefr_level = 'B2' AND english_term = 'wed';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'borrow';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'distribute';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'eliminate';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'exclude';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'owe';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'rent';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'repair';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'reserve';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'spare';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'submit';
UPDATE general_english_vocab SET topic_group = 'Verbs of Exchange & Removal' WHERE cefr_level = 'B2' AND english_term = 'tip';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'abroad';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'anywhere';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'aside';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'beside';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'east';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'elsewhere';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'everywhere';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'external';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'forth';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'internal';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'nearby';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'northern';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'regional';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'southern';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'upper';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'urban';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'via';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'west';
UPDATE general_english_vocab SET topic_group = 'Location & Direction' WHERE cefr_level = 'B2' AND english_term = 'zone';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'ancient';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'anymore';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'contemporary';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'era';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'frequently';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'immediate';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'journey';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'latter';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'meanwhile';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'originally';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'permanent';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'phase';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'previously';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'prior';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'rapidly';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'routine';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'sudden';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'temporary';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'till';
UPDATE general_english_vocab SET topic_group = 'Time & Sequence' WHERE cefr_level = 'B2' AND english_term = 'whenever';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'atmosphere';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'climate';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'cloud';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'coast';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'crop';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'forest';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'fuel';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'hill';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'ice';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'lake';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'landscape';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'root';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'rural';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'seed';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'sky';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'snow';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'soil';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'storm';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'B2' AND english_term = 'wild';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'beer';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'bottle';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'breakfast';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'diet';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'dish';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'fruit';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'meat';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'milk';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'protein';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'B2' AND english_term = 'tea';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'accommodation';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'bridge';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'column';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'core';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'county';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'desk';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'estate';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'factory';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'frame';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'gate';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'household';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'layer';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'neighborhood';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'panel';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'passage';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'port';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'roof';
UPDATE general_english_vocab SET topic_group = 'Structures, Places & Parts' WHERE cefr_level = 'B2' AND english_term = 'yard';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'aircraft';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'bike';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'bond';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'cable';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'chain';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'chemical';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'chip';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'coat';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'engine';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'hat';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'metal';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'plastic';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'plate';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'pocket';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'sheet';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'shirt';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'silver';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'string';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'toy';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'truck';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'wheel';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'wing';
UPDATE general_english_vocab SET topic_group = 'Objects, Materials & Clothing' WHERE cefr_level = 'B2' AND english_term = 'wire';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'advertisement';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'cast';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'channel';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'chart';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'drama';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'dramatic';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'edition';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'electronic';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'entertainment';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'episode';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'exhibit';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'exhibition';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'literature';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'mail';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'mobile';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'musical';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'online';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'publication';
UPDATE general_english_vocab SET topic_group = 'Arts, Media & Entertainment' WHERE cefr_level = 'B2' AND english_term = 'tennis';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'attractive';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'beauty';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'bright';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'capable';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'careful';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'classic';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'consistent';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'constant';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'formal';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'friendly';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'helpful';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'honest';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'ideal';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'lovely';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'moral';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'ordinary';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'practical';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'smart';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'soft';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (General)' WHERE cefr_level = 'B2' AND english_term = 'sweet';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'brown';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'empty';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'fat';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'gray';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'plain';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'sharp';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'solid';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'stable';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'steady';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'thick';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'thin';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'tight';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'uniform';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'wet';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Physical)' WHERE cefr_level = 'B2' AND english_term = 'yellow';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'considerable';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'enormous';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'extreme';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'grand';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'massive';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'minor';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'multiple';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'narrow';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'slight';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'substantial';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'tall';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'tiny';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Size & Scale)' WHERE cefr_level = 'B2' AND english_term = 'vast';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'crucial';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'fundamental';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'prime';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'principal';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'relevant';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'secondary';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'sufficient';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'suitable';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'typical';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'unique';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'valuable';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Importance)' WHERE cefr_level = 'B2' AND english_term = 'vital';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'FALSE';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'fault';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'hell';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'odd';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'rare';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'sensitive';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'severe';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'terrible';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'unable';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'unlike';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'unlikely';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'unknown';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'unusual';
UPDATE general_english_vocab SET topic_group = 'Descriptive Qualities (Negative)' WHERE cefr_level = 'B2' AND english_term = 'weak';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'absence';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'appearance';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'birth';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'childhood';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'existence';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'luck';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'lucky';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'personality';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'protection';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'reputation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'sexual';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'talent';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'tension';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (State & Condition)' WHERE cefr_level = 'B2' AND english_term = 'welfare';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'faith';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'honor';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'identity';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'impression';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'notion';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'origin';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'phenomenon';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'premise';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'proof';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'religion';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'soul';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'theme';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Ideas & Beliefs)' WHERE cefr_level = 'B2' AND english_term = 'vision';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'acquisition';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'agenda';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'association';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'characteristic';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'combination';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'comparison';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'convention';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'coverage';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'criteria';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'division';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'formula';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'framework';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'mechanism';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'outline';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'representation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'selection';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'sequence';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Systems & Structures)' WHERE cefr_level = 'B2' AND english_term = 'variation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'achievement';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'arrival';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'creation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'disaster';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'emergency';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'entry';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'incident';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'outcome';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'prize';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'prospect';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'reduction';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'relief';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'reward';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Events & Outcomes)' WHERE cefr_level = 'B2' AND english_term = 'victory';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'commitment';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'complaint';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'criticism';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'discipline';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'exception';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'excuse';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'expectation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'guarantee';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'instruction';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'intention';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'license';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'negotiation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'preparation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'priority';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'provision';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'recommendation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'resolution';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts (Formal)' WHERE cefr_level = 'B2' AND english_term = 'settlement';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'approximately';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'deeply';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'dozen';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'equally';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'heavily';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'inch';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'maximum';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'meter';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'minimum';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'plenty';
UPDATE general_english_vocab SET topic_group = 'Adverbs, Measurement & Quantity' WHERE cefr_level = 'B2' AND english_term = 'proportion';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'besides';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'furthermore';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'hence';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'merely';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'necessarily';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'nevertheless';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'primarily';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'secondly';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'somehow';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'somewhat';
UPDATE general_english_vocab SET topic_group = 'Connecting & Modifying Words' WHERE cefr_level = 'B2' AND english_term = 'ultimately';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'closely';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'effectively';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'efficient';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'entirely';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'increasingly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'largely';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'partly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'perfectly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'personally';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'properly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'reasonably';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'seriously';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'significantly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'slowly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'specifically';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'strongly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'surely';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'truly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'typically';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'virtually';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner' WHERE cefr_level = 'B2' AND english_term = 'widely';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'circle';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'crack';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'device';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'disk';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'electricity';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'gap';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'gene';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'hole';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'instrument';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'motion';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'mouse';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'pace';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'peak';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'pitch';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'plot';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'profile';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'rank';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'row';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'shot';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'signal';
UPDATE general_english_vocab SET topic_group = 'Miscellaneous Nouns & Verbs' WHERE cefr_level = 'B2' AND english_term = 'trace';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B2' AND english_term = 'educate';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B2' AND english_term = 'educational';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B2' AND english_term = 'examination';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B2' AND english_term = 'grade';
UPDATE general_english_vocab SET topic_group = 'Education & Learning' WHERE cefr_level = 'B2' AND english_term = 'graduate';

-- Step 3: Verify the distribution
SELECT topic_group, COUNT(*) as word_count FROM general_english_vocab WHERE cefr_level = 'B2' GROUP BY topic_group ORDER BY word_count DESC;

-- Step 4: Check for any remaining NULL values
SELECT COUNT(*) as remaining_nulls FROM general_english_vocab WHERE cefr_level = 'B2' AND topic_group IS NULL;

-- Step 5: Check for duplicate assignments
SELECT english_term, COUNT(*) as assignment_count FROM general_english_vocab WHERE cefr_level = 'B2' AND topic_group IS NOT NULL GROUP BY english_term HAVING COUNT(*) > 1;

-- Step 6: Total word count
SELECT COUNT(*) as total_assigned_words FROM general_english_vocab WHERE cefr_level = 'B2' AND topic_group IS NOT NULL;
