-- C1 Semantic Grouping
-- Assigns topic groups to 389 C1 words across 69 semantic groups
-- Validated: No duplicates, clean assignment

-- Step 1: Reset ALL C1 topic groups to NULL
UPDATE general_english_vocab
SET topic_group = NULL
WHERE cefr_level = 'C1';

-- Step 2: Assign topic groups to C1 words

UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'absolute';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'acceptable';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'accomplish';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'accurate';
UPDATE general_english_vocab SET topic_group = 'Actions & Changes' WHERE cefr_level = 'C1' AND english_term = 'adapt';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'adequate';
UPDATE general_english_vocab SET topic_group = 'Actions & Changes' WHERE cefr_level = 'C1' AND english_term = 'adjust';
UPDATE general_english_vocab SET topic_group = 'Feelings & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'admire';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'adviser';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'advocate';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'aggressive';
UPDATE general_english_vocab SET topic_group = 'Scientific & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'agricultural';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'alarm';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'album';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'alcohol';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'ally';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'analyst';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'anger';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'angle';
UPDATE general_english_vocab SET topic_group = 'Communication & Media' WHERE cefr_level = 'C1' AND english_term = 'announcement';
UPDATE general_english_vocab SET topic_group = 'Actions & Expectations' WHERE cefr_level = 'C1' AND english_term = 'anticipate';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'anxiety';
UPDATE general_english_vocab SET topic_group = 'Places & Architecture' WHERE cefr_level = 'C1' AND english_term = 'apartment';
UPDATE general_english_vocab SET topic_group = 'Communication & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'apologize';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'apparent';
UPDATE general_english_vocab SET topic_group = 'Feelings & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'approval';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'architecture';
UPDATE general_english_vocab SET topic_group = 'Actions & Tasks' WHERE cefr_level = 'C1' AND english_term = 'assign';
UPDATE general_english_vocab SET topic_group = 'Descriptions & Definitions' WHERE cefr_level = 'C1' AND english_term = 'attribute';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'automatically';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'awareness';
UPDATE general_english_vocab SET topic_group = 'Describing Feelings & Qualities' WHERE cefr_level = 'C1' AND english_term = 'awful';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'badly';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'barrier';
UPDATE general_english_vocab SET topic_group = 'Daily Routines & Hygiene' WHERE cefr_level = 'C1' AND english_term = 'bath';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'behave';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'bend';
UPDATE general_english_vocab SET topic_group = 'Describing Location & Movement' WHERE cefr_level = 'C1' AND english_term = 'beneath';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Actions' WHERE cefr_level = 'C1' AND english_term = 'bid';
UPDATE general_english_vocab SET topic_group = 'Physical Qualities & Conditions' WHERE cefr_level = 'C1' AND english_term = 'blind';
UPDATE general_english_vocab SET topic_group = 'Physical Qualities & Conditions' WHERE cefr_level = 'C1' AND english_term = 'bloody';
UPDATE general_english_vocab SET topic_group = 'Clothing & Apparel' WHERE cefr_level = 'C1' AND english_term = 'boot';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'boundary';
UPDATE general_english_vocab SET topic_group = 'Household & Domestic Items' WHERE cefr_level = 'C1' AND english_term = 'bowl';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'bread';
UPDATE general_english_vocab SET topic_group = 'Biological & Natural Terms' WHERE cefr_level = 'C1' AND english_term = 'breed';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'briefly';
UPDATE general_english_vocab SET topic_group = 'Describing Qualities' WHERE cefr_level = 'C1' AND english_term = 'brilliant';
UPDATE general_english_vocab SET topic_group = 'Communication & Media' WHERE cefr_level = 'C1' AND english_term = 'broadcast';
UPDATE general_english_vocab SET topic_group = 'Daily Routines & Hygiene' WHERE cefr_level = 'C1' AND english_term = 'brush';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'burden';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'burst';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'bury';
UPDATE general_english_vocab SET topic_group = 'Clothing & Apparel' WHERE cefr_level = 'C1' AND english_term = 'button';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'buyer';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'cake';
UPDATE general_english_vocab SET topic_group = 'Actions & Changes' WHERE cefr_level = 'C1' AND english_term = 'cancel';
UPDATE general_english_vocab SET topic_group = 'Clothing & Apparel' WHERE cefr_level = 'C1' AND english_term = 'cap';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'capability';
UPDATE general_english_vocab SET topic_group = 'Social Events & Occasions' WHERE cefr_level = 'C1' AND english_term = 'celebration';
UPDATE general_english_vocab SET topic_group = 'Social Events & Occasions' WHERE cefr_level = 'C1' AND english_term = 'ceremony';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Competition' WHERE cefr_level = 'C1' AND english_term = 'champion';
UPDATE general_english_vocab SET topic_group = 'Descriptions & Definitions' WHERE cefr_level = 'C1' AND english_term = 'characterize';
UPDATE general_english_vocab SET topic_group = 'Organizations & Groups' WHERE cefr_level = 'C1' AND english_term = 'charity';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'charm';
UPDATE general_english_vocab SET topic_group = 'Body & Health' WHERE cefr_level = 'C1' AND english_term = 'chest';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'chicken';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'cigarette';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Actions' WHERE cefr_level = 'C1' AND english_term = 'cite';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'classical';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'click';
UPDATE general_english_vocab SET topic_group = 'Medical & Scientific Terms' WHERE cefr_level = 'C1' AND english_term = 'clinical';
UPDATE general_english_vocab SET topic_group = 'Materials & Substances' WHERE cefr_level = 'C1' AND english_term = 'coal';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'compensation';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Competition' WHERE cefr_level = 'C1' AND english_term = 'competitor';
UPDATE general_english_vocab SET topic_group = 'Scientific & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'compound';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'comprehensive';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'compromise';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'confident';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'constantly';
UPDATE general_english_vocab SET topic_group = 'Descriptions & Definitions' WHERE cefr_level = 'C1' AND english_term = 'constitute';
UPDATE general_english_vocab SET topic_group = 'Communication & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'consult';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'consultant';
UPDATE general_english_vocab SET topic_group = 'Social Events & Occasions' WHERE cefr_level = 'C1' AND english_term = 'contest';
UPDATE general_english_vocab SET topic_group = 'Social & Cultural Terms' WHERE cefr_level = 'C1' AND english_term = 'conventional';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Actions' WHERE cefr_level = 'C1' AND english_term = 'correspond';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'counsel';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'counter';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'cousin';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'crazy';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'cream';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'creative';
UPDATE general_english_vocab SET topic_group = 'Communication & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'criticize';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'currency';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'curve';
UPDATE general_english_vocab SET topic_group = 'Social & Cultural Terms' WHERE cefr_level = 'C1' AND english_term = 'custom';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'dare';
UPDATE general_english_vocab SET topic_group = 'Technology & Internet' WHERE cefr_level = 'C1' AND english_term = 'database';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'dealer';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'dedicate';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'deficit';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'demonstration';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'dependent';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'deposit';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'depress';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'depth';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'desert';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'designer';
UPDATE general_english_vocab SET topic_group = 'Actions of Discovery & Investigation' WHERE cefr_level = 'C1' AND english_term = 'detect';
UPDATE general_english_vocab SET topic_group = 'Communication & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'dialog';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'dig';
UPDATE general_english_vocab SET topic_group = 'Technology & Internet' WHERE cefr_level = 'C1' AND english_term = 'digital';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'dimension';
UPDATE general_english_vocab SET topic_group = 'Negative Conditions & States' WHERE cefr_level = 'C1' AND english_term = 'dirty';
UPDATE general_english_vocab SET topic_group = 'Feelings & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'disagree';
UPDATE general_english_vocab SET topic_group = 'Actions of Discovery & Investigation' WHERE cefr_level = 'C1' AND english_term = 'discovery';
UPDATE general_english_vocab SET topic_group = 'Actions of Dismissal & Rejection' WHERE cefr_level = 'C1' AND english_term = 'dismiss';
UPDATE general_english_vocab SET topic_group = 'Medical & Scientific Terms' WHERE cefr_level = 'C1' AND english_term = 'disorder';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'disturb';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'divorce';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'drag';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'dramatically';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'dust';
UPDATE general_english_vocab SET topic_group = 'Geographical & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'eastern';
UPDATE general_english_vocab SET topic_group = 'Communication & Media' WHERE cefr_level = 'C1' AND english_term = 'edit';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'efficiency';
UPDATE general_english_vocab SET topic_group = 'Technology & Internet' WHERE cefr_level = 'C1' AND english_term = 'electric';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'embarrass';
UPDATE general_english_vocab SET topic_group = 'Feelings & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'embrace';
UPDATE general_english_vocab SET topic_group = 'Feelings & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'entertain';
UPDATE general_english_vocab SET topic_group = 'Actions of Authority & Rights' WHERE cefr_level = 'C1' AND english_term = 'entitle';
UPDATE general_english_vocab SET topic_group = 'Places & Architecture' WHERE cefr_level = 'C1' AND english_term = 'entrance';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'equation';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'essay';
UPDATE general_english_vocab SET topic_group = 'Organizations & Groups' WHERE cefr_level = 'C1' AND english_term = 'establishment';
UPDATE general_english_vocab SET topic_group = 'Social & Cultural Terms' WHERE cefr_level = 'C1' AND english_term = 'ethnic';
UPDATE general_english_vocab SET topic_group = 'Actions of Discovery & Investigation' WHERE cefr_level = 'C1' AND english_term = 'evaluate';
UPDATE general_english_vocab SET topic_group = 'Actions of Discovery & Investigation' WHERE cefr_level = 'C1' AND english_term = 'evaluation';
UPDATE general_english_vocab SET topic_group = 'Daily Routines & Hygiene' WHERE cefr_level = 'C1' AND english_term = 'everyday';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'evil';
UPDATE general_english_vocab SET topic_group = 'Scientific & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'evolution';
UPDATE general_english_vocab SET topic_group = 'Measurement & Comparison' WHERE cefr_level = 'C1' AND english_term = 'exact';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'exam';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'exceed';
UPDATE general_english_vocab SET topic_group = 'Growth & Development' WHERE cefr_level = 'C1' AND english_term = 'expansion';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'expenditure';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'exposure';
UPDATE general_english_vocab SET topic_group = 'Growth & Development' WHERE cefr_level = 'C1' AND english_term = 'extension';
UPDATE general_english_vocab SET topic_group = 'Measurement & Comparison' WHERE cefr_level = 'C1' AND english_term = 'extensive';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'extraordinary';
UPDATE general_english_vocab SET topic_group = 'Describing Feelings & Qualities' WHERE cefr_level = 'C1' AND english_term = 'fantastic';
UPDATE general_english_vocab SET topic_group = 'Social Events & Occasions' WHERE cefr_level = 'C1' AND english_term = 'festival';
UPDATE general_english_vocab SET topic_group = 'Light & Sound' WHERE cefr_level = 'C1' AND english_term = 'flash';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'float';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'flood';
UPDATE general_english_vocab SET topic_group = 'Communication & Media' WHERE cefr_level = 'C1' AND english_term = 'forecast';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'forever';
UPDATE general_english_vocab SET topic_group = 'Descriptions & Definitions' WHERE cefr_level = 'C1' AND english_term = 'format';
UPDATE general_english_vocab SET topic_group = 'Descriptions & Definitions' WHERE cefr_level = 'C1' AND english_term = 'formation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'fortune';
UPDATE general_english_vocab SET topic_group = 'Social & Cultural Terms' WHERE cefr_level = 'C1' AND english_term = 'foundation';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'frequency';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'frequent';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'friendship';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'frighten';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'fulfill';
UPDATE general_english_vocab SET topic_group = 'Household & Domestic Items' WHERE cefr_level = 'C1' AND english_term = 'furniture';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'gallery';
UPDATE general_english_vocab SET topic_group = 'Physical Objects & Equipment' WHERE cefr_level = 'C1' AND english_term = 'gear';
UPDATE general_english_vocab SET topic_group = 'Social & Cultural Terms' WHERE cefr_level = 'C1' AND english_term = 'gender';
UPDATE general_english_vocab SET topic_group = 'Scientific & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'genetic';
UPDATE general_english_vocab SET topic_group = 'Communication & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'gesture';
UPDATE general_english_vocab SET topic_group = 'Measurement & Comparison' WHERE cefr_level = 'C1' AND english_term = 'giant';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'glance';
UPDATE general_english_vocab SET topic_group = 'Religion & Beliefs' WHERE cefr_level = 'C1' AND english_term = 'god';
UPDATE general_english_vocab SET topic_group = 'Sports & Competition' WHERE cefr_level = 'C1' AND english_term = 'golf';
UPDATE general_english_vocab SET topic_group = 'Political & Social Actions' WHERE cefr_level = 'C1' AND english_term = 'govern';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'grab';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'gradually';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'grass';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'greatly';
UPDATE general_english_vocab SET topic_group = 'Negative Conditions & States' WHERE cefr_level = 'C1' AND english_term = 'harm';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'height';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Academia' WHERE cefr_level = 'C1' AND english_term = 'historian';
UPDATE general_english_vocab SET topic_group = 'Social & Cultural Terms' WHERE cefr_level = 'C1' AND english_term = 'historic';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'illegal';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'illustration';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'imagination';
UPDATE general_english_vocab SET topic_group = 'Feelings & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'impress';
UPDATE general_english_vocab SET topic_group = 'Describing Qualities' WHERE cefr_level = 'C1' AND english_term = 'impressive';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'incentive';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'independence';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'infant';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'infection';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'inflation';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'initially';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'injure';
UPDATE general_english_vocab SET topic_group = 'Describing Location & Movement' WHERE cefr_level = 'C1' AND english_term = 'inner';
UPDATE general_english_vocab SET topic_group = 'Growth & Development' WHERE cefr_level = 'C1' AND english_term = 'innovation';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'insight';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Actions' WHERE cefr_level = 'C1' AND english_term = 'interpret';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'intervention';
UPDATE general_english_vocab SET topic_group = 'Communication & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'invitation';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'involvement';
UPDATE general_english_vocab SET topic_group = 'Materials & Substances' WHERE cefr_level = 'C1' AND english_term = 'iron';
UPDATE general_english_vocab SET topic_group = 'Clothing & Apparel' WHERE cefr_level = 'C1' AND english_term = 'jacket';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'journal';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'joy';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'keen';
UPDATE general_english_vocab SET topic_group = 'Body & Health' WHERE cefr_level = 'C1' AND english_term = 'knee';
UPDATE general_english_vocab SET topic_group = 'Places of Science & Work' WHERE cefr_level = 'C1' AND english_term = 'laboratory';
UPDATE general_english_vocab SET topic_group = 'Organizations & Groups' WHERE cefr_level = 'C1' AND english_term = 'league';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'lecture';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Actions' WHERE cefr_level = 'C1' AND english_term = 'lend';
UPDATE general_english_vocab SET topic_group = 'Body & Health' WHERE cefr_level = 'C1' AND english_term = 'lip';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'literally';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'literary';
UPDATE general_english_vocab SET topic_group = 'Technology & Internet' WHERE cefr_level = 'C1' AND english_term = 'log';
UPDATE general_english_vocab SET topic_group = 'Physical Qualities & Conditions' WHERE cefr_level = 'C1' AND english_term = 'loose';
UPDATE general_english_vocab SET topic_group = 'Light & Sound' WHERE cefr_level = 'C1' AND english_term = 'loud';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'mad';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'march';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'margin';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'mate';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'mature';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'measurement';
UPDATE general_english_vocab SET topic_group = 'Organizations & Groups' WHERE cefr_level = 'C1' AND english_term = 'membership';
UPDATE general_english_vocab SET topic_group = 'Negative Conditions & States' WHERE cefr_level = 'C1' AND english_term = 'mess';
UPDATE general_english_vocab SET topic_group = 'Household & Domestic Items' WHERE cefr_level = 'C1' AND english_term = 'mirror';
UPDATE general_english_vocab SET topic_group = 'Materials & Substances' WHERE cefr_level = 'C1' AND english_term = 'mixture';
UPDATE general_english_vocab SET topic_group = 'Descriptions & Definitions' WHERE cefr_level = 'C1' AND english_term = 'mode';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'moderate';
UPDATE general_english_vocab SET topic_group = 'Actions & Changes' WHERE cefr_level = 'C1' AND english_term = 'modify';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'mortgage';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'motivate';
UPDATE general_english_vocab SET topic_group = 'Technology & Internet' WHERE cefr_level = 'C1' AND english_term = 'motor';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'mount';
UPDATE general_english_vocab SET topic_group = 'Body & Health' WHERE cefr_level = 'C1' AND english_term = 'muscle';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Art' WHERE cefr_level = 'C1' AND english_term = 'musician';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'mutual';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'naturally';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'newly';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'nowadays';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'obligation';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'occasionally';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'offense';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'opera';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'operator';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Competition' WHERE cefr_level = 'C1' AND english_term = 'opponent';
UPDATE general_english_vocab SET topic_group = 'Colors' WHERE cefr_level = 'C1' AND english_term = 'orange';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'overcome';
UPDATE general_english_vocab SET topic_group = 'Describing Location & Movement' WHERE cefr_level = 'C1' AND english_term = 'overseas';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'parallel';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'passion';
UPDATE general_english_vocab SET topic_group = 'Household & Domestic Items' WHERE cefr_level = 'C1' AND english_term = 'pen';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'perception';
UPDATE general_english_vocab SET topic_group = 'Actions of Authority & Rights' WHERE cefr_level = 'C1' AND english_term = 'permission';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'personnel';
UPDATE general_english_vocab SET topic_group = 'Scientific & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'philosophy';
UPDATE general_english_vocab SET topic_group = 'Animals' WHERE cefr_level = 'C1' AND english_term = 'pig';
UPDATE general_english_vocab SET topic_group = 'Physical Qualities & Conditions' WHERE cefr_level = 'C1' AND english_term = 'pile';
UPDATE general_english_vocab SET topic_group = 'Colors' WHERE cefr_level = 'C1' AND english_term = 'pink';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'planet';
UPDATE general_english_vocab SET topic_group = 'Places of Science & Work' WHERE cefr_level = 'C1' AND english_term = 'platform';
UPDATE general_english_vocab SET topic_group = 'Describing Feelings & Qualities' WHERE cefr_level = 'C1' AND english_term = 'pleasant';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'poem';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Art' WHERE cefr_level = 'C1' AND english_term = 'poet';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'pollution';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'portion';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'pose';
UPDATE general_english_vocab SET topic_group = 'Ownership & Possession' WHERE cefr_level = 'C1' AND english_term = 'possess';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'poverty';
UPDATE general_english_vocab SET topic_group = 'Communication & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'praise';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'precisely';
UPDATE general_english_vocab SET topic_group = 'Describing Feelings & Qualities' WHERE cefr_level = 'C1' AND english_term = 'preference';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'pregnant';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'privilege';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'profession';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'promotion';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'prompt';
UPDATE general_english_vocab SET topic_group = 'Geographical & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'province';
UPDATE general_english_vocab SET topic_group = 'Medical & Scientific Terms' WHERE cefr_level = 'C1' AND english_term = 'psychological';
UPDATE general_english_vocab SET topic_group = 'Travel & Leisure' WHERE cefr_level = 'C1' AND english_term = 'pub';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'publisher';
UPDATE general_english_vocab SET topic_group = 'Technology & Internet' WHERE cefr_level = 'C1' AND english_term = 'pump';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'pure';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'quantity';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'radical';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'C1' AND english_term = 'rail';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'random';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'rapid';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'rarely';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'ratio';
UPDATE general_english_vocab SET topic_group = 'Feelings & Social Interactions' WHERE cefr_level = 'C1' AND english_term = 'react';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'recovery';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'regret';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'regularly';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'reliable';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'remarkable';
UPDATE general_english_vocab SET topic_group = 'Describing Location & Movement' WHERE cefr_level = 'C1' AND english_term = 'remote';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'rescue';
UPDATE general_english_vocab SET topic_group = 'Actions & Opposition' WHERE cefr_level = 'C1' AND english_term = 'resist';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'resistance';
UPDATE general_english_vocab SET topic_group = 'Travel & Leisure' WHERE cefr_level = 'C1' AND english_term = 'resort';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'restriction';
UPDATE general_english_vocab SET topic_group = 'Actions & Changes' WHERE cefr_level = 'C1' AND english_term = 'reverse';
UPDATE general_english_vocab SET topic_group = 'Actions of Dismissal & Rejection' WHERE cefr_level = 'C1' AND english_term = 'rid';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Competition' WHERE cefr_level = 'C1' AND english_term = 'rival';
UPDATE general_english_vocab SET topic_group = 'Physical Qualities & Conditions' WHERE cefr_level = 'C1' AND english_term = 'rough';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'roughly';
UPDATE general_english_vocab SET topic_group = 'Negative Conditions & States' WHERE cefr_level = 'C1' AND english_term = 'ruin';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'salt';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'sand';
UPDATE general_english_vocab SET topic_group = 'Feelings & Emotions' WHERE cefr_level = 'C1' AND english_term = 'scare';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Academia' WHERE cefr_level = 'C1' AND english_term = 'scholar';
UPDATE general_english_vocab SET topic_group = 'Communication & Sound' WHERE cefr_level = 'C1' AND english_term = 'scream';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'seal';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'segment';
UPDATE general_english_vocab SET topic_group = 'Light & Sound' WHERE cefr_level = 'C1' AND english_term = 'shadow';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Business' WHERE cefr_level = 'C1' AND english_term = 'shareholder';
UPDATE general_english_vocab SET topic_group = 'Daily Routines & Hygiene' WHERE cefr_level = 'C1' AND english_term = 'shower';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'significance';
UPDATE general_english_vocab SET topic_group = 'Light & Sound' WHERE cefr_level = 'C1' AND english_term = 'silent';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'similarly';
UPDATE general_english_vocab SET topic_group = 'People & Roles in Art' WHERE cefr_level = 'C1' AND english_term = 'singer';
UPDATE general_english_vocab SET topic_group = 'Titles & Forms of Address' WHERE cefr_level = 'C1' AND english_term = 'sir';
UPDATE general_english_vocab SET topic_group = 'Clothing & Apparel' WHERE cefr_level = 'C1' AND english_term = 'skirt';
UPDATE general_english_vocab SET topic_group = 'Social & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'slave';
UPDATE general_english_vocab SET topic_group = 'Physical Qualities & Conditions' WHERE cefr_level = 'C1' AND english_term = 'smooth';
UPDATE general_english_vocab SET topic_group = 'Actions & Tasks' WHERE cefr_level = 'C1' AND english_term = 'specialize';
UPDATE general_english_vocab SET topic_group = 'Descriptions & Definitions' WHERE cefr_level = 'C1' AND english_term = 'specify';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'spin';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Actions' WHERE cefr_level = 'C1' AND english_term = 'sponsor';
UPDATE general_english_vocab SET topic_group = 'Measurement & Mathematics' WHERE cefr_level = 'C1' AND english_term = 'statistic';
UPDATE general_english_vocab SET topic_group = 'Materials & Substances' WHERE cefr_level = 'C1' AND english_term = 'steel';
UPDATE general_english_vocab SET topic_group = 'Causes & Origins' WHERE cefr_level = 'C1' AND english_term = 'stem';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'strain';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'stream';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'strip';
UPDATE general_english_vocab SET topic_group = 'Medical & Scientific Terms' WHERE cefr_level = 'C1' AND english_term = 'stroke';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'stupid';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Time & Frequency' WHERE cefr_level = 'C1' AND english_term = 'subsequent';
UPDATE general_english_vocab SET topic_group = 'Materials & Substances' WHERE cefr_level = 'C1' AND english_term = 'substance';
UPDATE general_english_vocab SET topic_group = 'Adverbs of Manner & Degree' WHERE cefr_level = 'C1' AND english_term = 'successfully';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'sugar';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Terms' WHERE cefr_level = 'C1' AND english_term = 'summary';
UPDATE general_english_vocab SET topic_group = 'Medical & Scientific Terms' WHERE cefr_level = 'C1' AND english_term = 'surgery';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'survival';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'sustain';
UPDATE general_english_vocab SET topic_group = 'Daily Routines & Hygiene' WHERE cefr_level = 'C1' AND english_term = 'sweep';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'symbol';
UPDATE general_english_vocab SET topic_group = 'Actions & Achievements' WHERE cefr_level = 'C1' AND english_term = 'tackle';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'C1' AND english_term = 'tank';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'tap';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'teenager';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'tendency';
UPDATE general_english_vocab SET topic_group = 'Geographical & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'territory';
UPDATE general_english_vocab SET topic_group = 'Medical & Scientific Terms' WHERE cefr_level = 'C1' AND english_term = 'therapy';
UPDATE general_english_vocab SET topic_group = 'Body & Health' WHERE cefr_level = 'C1' AND english_term = 'throat';
UPDATE general_english_vocab SET topic_group = 'Places & Architecture' WHERE cefr_level = 'C1' AND english_term = 'tower';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'C1' AND english_term = 'trail';
UPDATE general_english_vocab SET topic_group = 'Actions & Changes' WHERE cefr_level = 'C1' AND english_term = 'transform';
UPDATE general_english_vocab SET topic_group = 'Actions & Changes' WHERE cefr_level = 'C1' AND english_term = 'transition';
UPDATE general_english_vocab SET topic_group = 'Communication & Academic Actions' WHERE cefr_level = 'C1' AND english_term = 'translate';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'trap';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'C1' AND english_term = 'tube';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'tune';
UPDATE general_english_vocab SET topic_group = 'Family & Relationships' WHERE cefr_level = 'C1' AND english_term = 'twin';
UPDATE general_english_vocab SET topic_group = 'Physical Actions & Movement' WHERE cefr_level = 'C1' AND english_term = 'twist';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'universal';
UPDATE general_english_vocab SET topic_group = 'Nature & Environment' WHERE cefr_level = 'C1' AND english_term = 'valley';
UPDATE general_english_vocab SET topic_group = 'Travel & Transport' WHERE cefr_level = 'C1' AND english_term = 'van';
UPDATE general_english_vocab SET topic_group = 'Food & Drink' WHERE cefr_level = 'C1' AND english_term = 'vegetable';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Actions' WHERE cefr_level = 'C1' AND english_term = 'venture';
UPDATE general_english_vocab SET topic_group = 'Comparison & Opposition' WHERE cefr_level = 'C1' AND english_term = 'versus';
UPDATE general_english_vocab SET topic_group = 'Negative Conditions & States' WHERE cefr_level = 'C1' AND english_term = 'vice';
UPDATE general_english_vocab SET topic_group = 'Describing Personality & Behavior' WHERE cefr_level = 'C1' AND english_term = 'violent';
UPDATE general_english_vocab SET topic_group = 'Medical & Scientific Terms' WHERE cefr_level = 'C1' AND english_term = 'virus';
UPDATE general_english_vocab SET topic_group = 'Describing Qualities' WHERE cefr_level = 'C1' AND english_term = 'visible';
UPDATE general_english_vocab SET topic_group = 'Art, Music & Media' WHERE cefr_level = 'C1' AND english_term = 'visual';
UPDATE general_english_vocab SET topic_group = 'Abstract Concepts & Qualities' WHERE cefr_level = 'C1' AND english_term = 'weakness';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'wealth';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Terms' WHERE cefr_level = 'C1' AND english_term = 'wealthy';
UPDATE general_english_vocab SET topic_group = 'Technology & Internet' WHERE cefr_level = 'C1' AND english_term = 'web';
UPDATE general_english_vocab SET topic_group = 'Measurement & Comparison' WHERE cefr_level = 'C1' AND english_term = 'weigh';
UPDATE general_english_vocab SET topic_group = 'Geographical & Political Terms' WHERE cefr_level = 'C1' AND english_term = 'western';
UPDATE general_english_vocab SET topic_group = 'Financial & Business Actions' WHERE cefr_level = 'C1' AND english_term = 'withdraw';
UPDATE general_english_vocab SET topic_group = 'Health & Well-being' WHERE cefr_level = 'C1' AND english_term = 'wound';
UPDATE general_english_vocab SET topic_group = 'Daily Routines & Hygiene' WHERE cefr_level = 'C1' AND english_term = 'wrap';

-- Step 3: Verify the distribution
SELECT topic_group, COUNT(*) as word_count FROM general_english_vocab WHERE cefr_level = 'C1' GROUP BY topic_group ORDER BY word_count DESC;

-- Step 4: Check for any remaining NULL values
SELECT COUNT(*) as remaining_nulls FROM general_english_vocab WHERE cefr_level = 'C1' AND topic_group IS NULL;

-- Step 5: Check for duplicate assignments
SELECT english_term, COUNT(*) as assignment_count FROM general_english_vocab WHERE cefr_level = 'C1' AND topic_group IS NOT NULL GROUP BY english_term HAVING COUNT(*) > 1;

-- Step 6: Total word count
SELECT COUNT(*) as total_assigned_words FROM general_english_vocab WHERE cefr_level = 'C1' AND topic_group IS NOT NULL;
