[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build || true"]

[start]
cmd = "npm start"
